'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, BarChart3, Bot, CalendarDays, CheckCircle2, FileText, Flag, Home, KeyRound, MessageSquare, Settings2, ShieldCheck, SlidersHorizontal, Users, WalletCards } from 'lucide-react'
import { DashboardShell, MetricCard, SectionCard } from '@/components/dashboard-shell'

type ManagementRole = 'property-owner' | 'agent' | 'admin' | 'super-admin'
type DashboardData = { metrics?: Record<string, number>; properties?: Array<Record<string, unknown>>; inquiries?: Array<Record<string, unknown>>; reports?: Array<Record<string, unknown>>; audit?: Array<Record<string, unknown>> }

const copy = {
  'property-owner': { role: 'Property Owner' as const, title: 'Kelola portofolio properti Anda.', description: 'Pantau properti, percakapan, jadwal, dan publikasi listing dari satu ruang kerja.', sections: [['properties', 'Properti Saya', Home], ['inquiries', 'Pertanyaan', MessageSquare], ['calendar', 'Kalender', CalendarDays], ['list', 'Pasang Properti', FileText]] },
  agent: { role: 'Agent' as const, title: 'Bangun pipeline properti yang lebih kuat.', description: 'Kelola prospek, kinerja listing, dan penagihan komisi secara terpusat.', sections: [['crm', 'CRM Prospek', Users], ['analytics', 'Analitik', BarChart3], ['billing', 'Penagihan', WalletCards]] },
  admin: { role: 'Admin' as const, title: 'Jaga kualitas dan keamanan marketplace.', description: 'Moderasi listing, kelola pengguna, tindak laporan, dan pantau sistem AI.', sections: [['moderation', 'Moderasi Listing', ShieldCheck], ['users', 'Pengguna & Agen', Users], ['reports', 'Laporan & Penipuan', AlertTriangle], ['ai', 'Pemantauan AI', Bot]] },
  'super-admin': { role: 'Super Admin' as const, title: 'Kendalikan fondasi platform Homy.', description: 'Atur akses, konfigurasi, audit, dan fitur platform dari pusat kendali.', sections: [['roles', 'Peran & Izin', KeyRound], ['system', 'Konfigurasi Sistem', Settings2], ['audit', 'Log Audit', FileText], ['flags', 'Feature Flag', SlidersHorizontal]] },
} as const

export function DashboardManagementPage({ type }: { type: ManagementRole }) {
  const [data, setData] = useState<DashboardData>({})
  const [loading, setLoading] = useState(true)
  const config = copy[type]
  useEffect(() => { fetch(`/api/dashboard/${type}`).then((response) => response.json()).then(setData).catch(() => setData({})).finally(() => setLoading(false)) }, [type])
  const metricEntries = type === 'property-owner' ? [['Properti saya', 'properties'], ['Listing aktif', 'publishedProperties'], ['Pertanyaan', 'inquiries'], ['Kunjungan mendatang', 'upcomingVisits']] : type === 'agent' ? [['Listing aktif', 'activeListings'], ['Prospek baru', 'newLeads'], ['Konversi', 'conversionRate'], ['Pendapatan', 'revenue']] : type === 'admin' ? [['Menunggu moderasi', 'pendingApprovals'], ['Pengguna', 'activeUsers'], ['Laporan terbuka', 'openReports'], ['Akurasi AI', 'aiAccuracy']] : [['Pengguna', 'users'], ['Properti', 'properties'], ['Event audit', 'auditEvents'], ['Feature flag', 'featureFlags']]
  const sectionContent = (id: string) => { if (id === 'properties' || id === 'moderation') return <div className="space-y-3">{(data.properties ?? []).map((item, index) => <div key={String(item.id ?? index)} className="flex flex-col gap-1 rounded-xl bg-[#f7f3ec] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-[#20332c]">{String(item.title ?? 'Listing properti')}</p><p className="text-sm text-[#718078]">{String(item.city ?? item.status ?? 'Menunggu data')}</p></div><span className="rounded-full bg-[#edf2ed] px-3 py-1 text-xs font-semibold text-[#0b3d2e]">{String(item.status ?? 'aktif')}</span></div>)}{!loading && !(data.properties?.length) && <p className="rounded-xl bg-[#f7f3ec] p-4 text-sm text-[#718078]">Belum ada data yang perlu ditampilkan.</p>}</div>
    if (id === 'inquiries' || id === 'crm') return <div className="space-y-3">{(data.inquiries ?? []).map((item, index) => <div key={String(item.id ?? index)} className="rounded-xl border border-[#eee7dc] p-4"><div className="flex items-center justify-between"><p className="font-semibold">Percakapan properti</p><span className="text-xs font-semibold text-[#4e866d]">{String(item.status ?? 'baru')}</span></div><p className="mt-2 text-sm text-[#718078]">{String(item.message ?? 'Belum ada pesan')}</p></div>)}{!loading && !(data.inquiries?.length) && <p className="rounded-xl bg-[#f7f3ec] p-4 text-sm text-[#718078]">Belum ada percakapan.</p>}</div>
    if (id === 'reports') return <div className="space-y-3">{(data.reports ?? []).map((item, index) => <div key={String(item.id ?? index)} className="flex items-center gap-3 rounded-xl bg-[#fff4d6] p-4"><Flag className="text-[#9b762a]" /><div><p className="font-semibold">{String(item.reason ?? 'Laporan baru')}</p><p className="text-xs text-[#718078]">Status: {String(item.status ?? 'open')}</p></div></div>)}</div>
    if (id === 'audit') return <div className="space-y-3">{(data.audit ?? []).map((item, index) => <div key={String(item.id ?? index)} className="flex gap-3 border-b border-[#eee7dc] pb-3"><CheckCircle2 className="text-[#4e866d]" /><div><p className="font-semibold">{String(item.action ?? 'Aktivitas sistem')}</p><p className="text-xs text-[#718078]">{String(item.entity_type ?? 'sistem')} · {String(item.created_at ?? '')}</p></div></div>)}</div>
    return <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#f7f3ec] p-4"><p className="font-semibold">{id === 'calendar' ? 'Jadwal terhubung' : id === 'billing' ? 'Ringkasan penagihan' : id === 'analytics' ? 'Tren performa' : id === 'ai' ? 'Status pemantauan' : 'Pengaturan aktif'}</p><p className="mt-2 text-sm text-[#718078]">Data akan diperbarui otomatis dari aktivitas platform dan database.</p></div><div className="rounded-xl border border-dashed border-[#d8ccbb] p-4"><p className="font-semibold text-[#0b3d2e]">Tindakan berikutnya</p><p className="mt-2 text-sm text-[#718078]">Buka modul ini untuk mengelola detail dan memperbarui status.</p></div></div> }
  return <DashboardShell role={config.role}><div className="mb-8"><p className="text-sm text-[#718078]">Ruang kerja Homy</p><h2 className="mt-1 font-serif text-4xl text-[#0b3d2e]">{config.title}</h2><p className="mt-2 max-w-2xl text-[#718078]">{config.description}</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metricEntries.map(([label, key], index) => <MetricCard key={key} label={label} value={loading ? '—' : String(data.metrics?.[key] ?? 0)} change="Data terbaru" icon={(['home', 'users', 'chart', 'wallet'] as const)[index]} />)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2">{config.sections.map(([id, title, Icon]) => <SectionCard key={id} id={id} title={title} action="Buka modul"><div className="mb-4 flex items-center gap-2 text-sm text-[#718078]"><Icon className="size-4 text-[#0b3d2e]" /> Modul terhubung ke Supabase</div>{sectionContent(id)}</SectionCard>)}</div></DashboardShell> }
