'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, BarChart3, Bot, CalendarDays, CheckCircle2, FileSignature, FileText, Flag, Home, KeyRound, MessageSquare, Settings2, ShieldCheck, SlidersHorizontal, Users, WalletCards } from 'lucide-react'
import { DashboardShell, SectionCard } from '@/components/dashboard-shell'
import { ModerationQueue } from '@/components/moderation-queue'
import { MyListings } from '@/components/my-listings'
import { createClient } from '@/lib/supabase/client'

type ManagementRole = 'property-owner' | 'agent' | 'admin' | 'super-admin'
type DashboardData = { metrics?: Record<string, number>; properties?: Array<Record<string, unknown>>; inquiries?: Array<Record<string, unknown>>; reports?: Array<Record<string, unknown>>; audit?: Array<Record<string, unknown>> }

const copy = {
  'property-owner': { role: 'Property Owner' as const, title: 'Kelola portofolio properti Anda.', description: 'Pantau properti, percakapan, jadwal, dan publikasi listing dari satu ruang kerja.', sections: [['properties', 'Properti Saya', Home], ['inquiries', 'Pertanyaan', MessageSquare], ['calendar', 'Kalender', CalendarDays], ['list', 'Pasang Properti', FileText], ['agreement', 'Perjanjian Kerjasama', FileSignature]] },
  agent: { role: 'Agent' as const, title: 'Bangun pipeline properti yang lebih kuat.', description: 'Kelola prospek, kinerja listing, dan penagihan komisi secara terpusat.', sections: [['properties', 'Listing Saya', Home], ['list', 'Pasang Properti', FileText], ['agreement', 'Perjanjian Kerjasama', FileSignature], ['crm', 'CRM Prospek', Users], ['analytics', 'Analitik', BarChart3], ['billing', 'Penagihan', WalletCards]] },
  admin: { role: 'Admin' as const, title: 'Jaga kualitas dan keamanan marketplace.', description: 'Moderasi listing, kelola pengguna, tindak laporan, dan pantau sistem AI.', sections: [['moderation', 'Moderasi Listing', ShieldCheck], ['users', 'Pengguna & Agen', Users], ['reports', 'Laporan & Penipuan', AlertTriangle], ['ai', 'Pemantauan AI', Bot]] },
  'super-admin': { role: 'Super Admin' as const, title: 'Kendalikan fondasi platform Homy.', description: 'Atur akses, konfigurasi, audit, dan fitur platform dari pusat kendali.', sections: [['roles', 'Peran & Izin', KeyRound], ['system', 'Konfigurasi Sistem', Settings2], ['audit', 'Log Audit', FileText], ['flags', 'Feature Flag', SlidersHorizontal]] },
} as const

export function DashboardManagementPage({ type }: { type: ManagementRole }) {
  const [data, setData] = useState<DashboardData>({})
  const [loading, setLoading] = useState(true)
  const [agreements, setAgreements] = useState<string[]>([])
  const config = copy[type]
  useEffect(() => { fetch(`/api/dashboard/${type}`).then((response) => response.json()).then(setData).catch(() => setData({})).finally(() => setLoading(false)) }, [type])
  useEffect(() => {
    const supabase = createClient() as any
    supabase.auth.getUser().then(async ({ data: userData }: any) => {
      const user = userData?.user
      if (!user) return
      const { data: rows } = await supabase.from('partner_agreements').select('role,status').eq('user_id', user.id).eq('status', 'active')
      if (Array.isArray(rows)) setAgreements(rows.map((row: { role: string }) => row.role))
    }).catch(() => undefined)
  }, [])
  const sectionContent = (id: string) => {
    if (id === 'moderation') return <ModerationQueue />
    if (id === 'properties') return <MyListings items={(data.properties ?? []) as Array<{ id: string; title?: string; status?: string }>} />
    if (id === 'inquiries' || id === 'crm') return <div className="space-y-3">{(data.inquiries ?? []).map((item, index) => <div key={String(item.id ?? index)} className="rounded-xl border border-[#eee7dc] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">Prospek properti</p><p className="mt-1 text-xs text-[#718078]">ID properti: {String(item.property_id ?? '—')}</p></div><span className="rounded-full bg-[#edf2ed] px-2.5 py-1 text-xs font-semibold text-[#4e866d]">{String(item.status ?? 'baru')}</span></div><p className="mt-3 text-sm leading-6 text-[#718078]">{String(item.message ?? 'Belum ada pesan')}</p><div className="mt-3 flex gap-2"><button className="rounded-lg bg-[#0b3d2e] px-3 py-1.5 text-xs font-semibold text-white">Tindak lanjuti</button><button className="rounded-lg border border-[#d8ccbb] px-3 py-1.5 text-xs font-semibold">Catat aktivitas</button></div></div>)}{!loading && !(data.inquiries?.length) && <p className="rounded-xl bg-[#f7f3ec] p-4 text-sm text-[#718078]">Belum ada percakapan.</p>}</div>
    if (id === 'reports') return <div className="space-y-3">{(data.reports ?? []).map((item, index) => <div key={String(item.id ?? index)} className="flex items-start gap-3 rounded-xl bg-[#fff4d6] p-4"><Flag className="mt-0.5 text-[#9b762a]" /><div className="flex-1"><div className="flex items-center justify-between gap-3"><p className="font-semibold">{String(item.reason ?? 'Laporan baru')}</p><span className="text-xs font-semibold text-[#9b762a]">{String(item.status ?? 'open')}</span></div><p className="mt-1 text-xs text-[#718078]">Diterima {String(item.created_at ?? 'baru-baru ini')}</p><button className="mt-3 rounded-lg border border-[#d8ccbb] px-3 py-1.5 text-xs font-semibold">Buka kasus</button></div></div>)}{!loading && !(data.reports?.length) && <p className="rounded-xl bg-[#f7f3ec] p-4 text-sm text-[#718078]">Tidak ada laporan terbuka.</p>}</div>
    if (id === 'audit') return <div className="space-y-3">{(data.audit ?? []).map((item, index) => <div key={String(item.id ?? index)} className="flex gap-3 border-b border-[#eee7dc] pb-3"><CheckCircle2 className="mt-0.5 text-[#4e866d]" /><div><p className="font-semibold">{String(item.action ?? 'Aktivitas sistem')}</p><p className="mt-1 text-xs text-[#718078]">{String(item.entity_type ?? 'sistem')} · {String(item.created_at ?? '')}</p></div></div>)}{!loading && !(data.audit?.length) && <p className="rounded-xl bg-[#f7f3ec] p-4 text-sm text-[#718078]">Belum ada aktivitas audit.</p>}</div>
    if (id === 'agreement') return <div className="rounded-xl bg-[#f7f3ec] p-4 sm:p-5"><div className="flex items-center gap-2"><FileSignature className="size-5 text-[#0b3d2e]" /><p className="font-semibold text-[#0b3d2e]">Surat Perjanjian Kerja Sama</p></div>{(type === 'agent' || type === 'property-owner') && agreements.includes(type === 'agent' ? 'agent' : 'property_owner') ? <><p className="mt-2 text-sm leading-6 text-[#718078]">Perjanjian Anda sudah aktif. Komisi penjualan 0,5% dari harga jual dan kewajiban pelaporan transaksi berlaku.</p><span className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#edf2ed] px-3 py-1 text-xs font-semibold text-[#4e866d]"><CheckCircle2 className="size-4" /> Perjanjian aktif</span><a href="/agreement" className="ml-3 inline-flex text-xs font-semibold text-[#0b3d2e] underline">Lihat / perbarui</a></> : <><p className="mt-2 text-sm leading-6 text-[#718078]">Wajib sebelum memasang properti: daftar sebagai Mitra, tanda tangani perjanjian, setujui komisi penjualan 0,5%, dan laporkan setiap transaksi kepada Homy.</p><a href={`/agreement?role=${type === 'agent' ? 'agent' : 'property_owner'}&next=/list`} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#0b3d2e] px-4 py-2 text-sm font-semibold text-white hover:bg-[#14553f]">Tanda tangani perjanjian</a><span className="ml-3 inline-flex rounded-full bg-[#fff7e3] px-3 py-1 text-xs font-semibold text-[#9b762a]">Belum ditandatangani</span></>}</div>
    const panels: Record<string, [string, string, string]> = { calendar: ['Agenda kunjungan', 'Pantau jadwal kunjungan, konfirmasi waktu, dan siapkan catatan untuk setiap calon pembeli.', 'Buka kalender'], list: ['Publikasikan properti', 'Lengkapi foto, harga, lokasi, dan status listing sebelum ditayangkan ke marketplace.', 'Buat listing'], analytics: ['Kinerja pipeline', 'Bandingkan listing aktif, prospek masuk, respons, dan konversi untuk menentukan prioritas.', 'Lihat laporan'], billing: ['Penagihan & komisi', 'Pantau saldo, invoice, status pembayaran, dan riwayat transaksi dalam satu tempat.', 'Kelola penagihan'], users: ['Direktori pengguna', 'Cari profil, peran, status verifikasi, dan aktivitas pengguna platform.', 'Kelola pengguna'], ai: ['Kesehatan sistem AI', 'Pantau antrean analisis, akurasi deteksi, dan kejadian yang perlu ditinjau manual.', 'Buka pemantauan'], roles: ['Matriks akses', 'Kelola peran, izin, dan cakupan akses agar setiap pengguna hanya melihat fungsi yang sesuai.', 'Kelola izin'], system: ['Konfigurasi platform', 'Atur parameter marketplace, notifikasi, keamanan, dan integrasi inti Homy.', 'Buka konfigurasi'], flags: ['Kontrol fitur', 'Aktifkan atau nonaktifkan fitur secara bertahap dan pantau dampaknya.', 'Kelola flag'] }
    const [heading, description, action] = panels[id] ?? ['Modul terhubung', 'Data diperbarui dari aktivitas platform dan database.', 'Buka modul']
    return <div className="grid gap-3 md:grid-cols-[1.4fr_1fr]"><div className="rounded-xl bg-[#f7f3ec] p-4 sm:p-5"><p className="font-semibold text-[#0b3d2e]">{heading}</p><p className="mt-2 text-sm leading-6 text-[#718078]">{description}</p>{id === 'list' ? <a href="/list" className="mt-4 inline-flex rounded-lg bg-[#0b3d2e] px-4 py-2 text-sm font-semibold text-white hover:bg-[#14553f]">{action}</a> : <button className="mt-4 rounded-lg bg-[#0b3d2e] px-4 py-2 text-sm font-semibold text-white">{action}</button>}</div><div className="rounded-xl border border-dashed border-[#d8ccbb] p-4 sm:p-5"><p className="font-semibold text-[#0b3d2e]">Status sinkronisasi</p><p className="mt-2 text-sm text-[#718078]">Data terbaru dibaca dari Supabase. Perubahan akses memerlukan validasi sesuai role.</p><span className="mt-4 inline-flex rounded-full bg-[#edf2ed] px-3 py-1 text-xs font-semibold text-[#4e866d]">Terhubung</span></div></div>
  }
  return <DashboardShell role={config.role}><div className="mb-5 sm:mb-8"><p className="text-sm text-[#718078]">Ruang kerja Homy</p><h2 className="mt-1 font-serif text-2xl sm:text-4xl text-[#0b3d2e]">{config.title}</h2><p className="mt-2 max-w-2xl text-[#718078]">{config.description}</p></div><div className="mt-6 grid gap-4 sm:gap-6 xl:grid-cols-2">{config.sections.map(([id, title, Icon]) => <SectionCard key={id} id={id} title={title} action="Buka modul"><div className="mb-4 flex items-center gap-2 text-sm text-[#718078]"><Icon className="size-4 text-[#0b3d2e]" /> Modul terhubung ke Supabase</div>{sectionContent(id)}</SectionCard>)}</div></DashboardShell> }
