// AUTO-GENERATED dari wilayah.id (BPS). Jangan edit manual.
// 514 kabupaten/kota seluruh Indonesia untuk halaman SEO lokasi.
export type Region = { province: string; city: string }

export const REGIONS: Region[] = [
  { province: "Aceh", city: "Kabupaten Aceh Selatan" },
  { province: "Aceh", city: "Kabupaten Aceh Tenggara" },
  { province: "Aceh", city: "Kabupaten Aceh Timur" },
  { province: "Aceh", city: "Kabupaten Aceh Tengah" },
  { province: "Aceh", city: "Kabupaten Aceh Barat" },
  { province: "Aceh", city: "Kabupaten Aceh Besar" },
  { province: "Aceh", city: "Kabupaten Pidie" },
  { province: "Aceh", city: "Kabupaten Aceh Utara" },
  { province: "Aceh", city: "Kabupaten Simeulue" },
  { province: "Aceh", city: "Kabupaten Aceh Singkil" },
  { province: "Aceh", city: "Kabupaten Bireuen" },
  { province: "Aceh", city: "Kabupaten Aceh Barat Daya" },
  { province: "Aceh", city: "Kabupaten Gayo Lues" },
  { province: "Aceh", city: "Kabupaten Aceh Jaya" },
  { province: "Aceh", city: "Kabupaten Nagan Raya" },
  { province: "Aceh", city: "Kabupaten Aceh Tamiang" },
  { province: "Aceh", city: "Kabupaten Bener Meriah" },
  { province: "Aceh", city: "Kabupaten Pidie Jaya" },
  { province: "Aceh", city: "Kota Banda Aceh" },
  { province: "Aceh", city: "Kota Sabang" },
  { province: "Aceh", city: "Kota Lhokseumawe" },
  { province: "Aceh", city: "Kota Langsa" },
  { province: "Aceh", city: "Kota Subulussalam" },
  { province: "Sumatera Utara", city: "Kabupaten Tapanuli Tengah" },
  { province: "Sumatera Utara", city: "Kabupaten Tapanuli Utara" },
  { province: "Sumatera Utara", city: "Kabupaten Tapanuli Selatan" },
  { province: "Sumatera Utara", city: "Kabupaten Nias" },
  { province: "Sumatera Utara", city: "Kabupaten Langkat" },
  { province: "Sumatera Utara", city: "Kabupaten Karo" },
  { province: "Sumatera Utara", city: "Kabupaten Deli Serdang" },
  { province: "Sumatera Utara", city: "Kabupaten Simalungun" },
  { province: "Sumatera Utara", city: "Kabupaten Asahan" },
  { province: "Sumatera Utara", city: "Kabupaten Labuhanbatu" },
  { province: "Sumatera Utara", city: "Kabupaten Dairi" },
  { province: "Sumatera Utara", city: "Kabupaten Toba" },
  { province: "Sumatera Utara", city: "Kabupaten Mandailing Natal" },
  { province: "Sumatera Utara", city: "Kabupaten Nias Selatan" },
  { province: "Sumatera Utara", city: "Kabupaten Pakpak Bharat" },
  { province: "Sumatera Utara", city: "Kabupaten Humbang Hasundutan" },
  { province: "Sumatera Utara", city: "Kabupaten Samosir" },
  { province: "Sumatera Utara", city: "Kabupaten Serdang Bedagai" },
  { province: "Sumatera Utara", city: "Kabupaten Batu Bara" },
  { province: "Sumatera Utara", city: "Kabupaten Padang Lawas Utara" },
  { province: "Sumatera Utara", city: "Kabupaten Padang Lawas" },
  { province: "Sumatera Utara", city: "Kabupaten Labuhanbatu Selatan" },
  { province: "Sumatera Utara", city: "Kabupaten Labuhanbatu Utara" },
  { province: "Sumatera Utara", city: "Kabupaten Nias Utara" },
  { province: "Sumatera Utara", city: "Kabupaten Nias Barat" },
  { province: "Sumatera Utara", city: "Kota Medan" },
  { province: "Sumatera Utara", city: "Kota Pematangsiantar" },
  { province: "Sumatera Utara", city: "Kota Sibolga" },
  { province: "Sumatera Utara", city: "Kota Tanjungbalai" },
  { province: "Sumatera Utara", city: "Kota Binjai" },
  { province: "Sumatera Utara", city: "Kota Tebing Tinggi" },
  { province: "Sumatera Utara", city: "Kota Padangsidimpuan" },
  { province: "Sumatera Utara", city: "Kota Gunungsitoli" },
  { province: "Sumatera Barat", city: "Kabupaten Pesisir Selatan" },
  { province: "Sumatera Barat", city: "Kabupaten Solok" },
  { province: "Sumatera Barat", city: "Kabupaten Sijunjung" },
  { province: "Sumatera Barat", city: "Kabupaten Tanah Datar" },
  { province: "Sumatera Barat", city: "Kabupaten Padang Pariaman" },
  { province: "Sumatera Barat", city: "Kabupaten Agam" },
  { province: "Sumatera Barat", city: "Kabupaten Lima Puluh Kota" },
  { province: "Sumatera Barat", city: "Kabupaten Pasaman" },
  { province: "Sumatera Barat", city: "Kabupaten Kepulauan Mentawai" },
  { province: "Sumatera Barat", city: "Kabupaten Dharmasraya" },
  { province: "Sumatera Barat", city: "Kabupaten Solok Selatan" },
  { province: "Sumatera Barat", city: "Kabupaten Pasaman Barat" },
  { province: "Sumatera Barat", city: "Kota Padang" },
  { province: "Sumatera Barat", city: "Kota Solok" },
  { province: "Sumatera Barat", city: "Kota Sawahlunto" },
  { province: "Sumatera Barat", city: "Kota Padang Panjang" },
  { province: "Sumatera Barat", city: "Kota Bukittinggi" },
  { province: "Sumatera Barat", city: "Kota Payakumbuh" },
  { province: "Sumatera Barat", city: "Kota Pariaman" },
  { province: "Riau", city: "Kabupaten Kampar" },
  { province: "Riau", city: "Kabupaten Indragiri Hulu" },
  { province: "Riau", city: "Kabupaten Bengkalis" },
  { province: "Riau", city: "Kabupaten Indragiri Hilir" },
  { province: "Riau", city: "Kabupaten Pelalawan" },
  { province: "Riau", city: "Kabupaten Rokan Hulu" },
  { province: "Riau", city: "Kabupaten Rokan Hilir" },
  { province: "Riau", city: "Kabupaten Siak" },
  { province: "Riau", city: "Kabupaten Kuantan Singingi" },
  { province: "Riau", city: "Kabupaten Kepulauan Meranti" },
  { province: "Riau", city: "Kota Pekanbaru" },
  { province: "Riau", city: "Kota Dumai" },
  { province: "Jambi", city: "Kabupaten Kerinci" },
  { province: "Jambi", city: "Kabupaten Merangin" },
  { province: "Jambi", city: "Kabupaten Sarolangun" },
  { province: "Jambi", city: "Kabupaten Batanghari" },
  { province: "Jambi", city: "Kabupaten Muaro Jambi" },
  { province: "Jambi", city: "Kabupaten Tanjung Jabung Barat" },
  { province: "Jambi", city: "Kabupaten Tanjung Jabung Timur" },
  { province: "Jambi", city: "Kabupaten Bungo" },
  { province: "Jambi", city: "Kabupaten Tebo" },
  { province: "Jambi", city: "Kota Jambi" },
  { province: "Jambi", city: "Kota Sungai Penuh" },
  { province: "Sumatera Selatan", city: "Kabupaten Ogan Komering Ulu" },
  { province: "Sumatera Selatan", city: "Kabupaten Ogan Komering Ilir" },
  { province: "Sumatera Selatan", city: "Kabupaten Muara Enim" },
  { province: "Sumatera Selatan", city: "Kabupaten Lahat" },
  { province: "Sumatera Selatan", city: "Kabupaten Musi Rawas" },
  { province: "Sumatera Selatan", city: "Kabupaten Musi Banyuasin" },
  { province: "Sumatera Selatan", city: "Kabupaten Banyuasin" },
  { province: "Sumatera Selatan", city: "Kabupaten Ogan Komering Ulu Timur" },
  { province: "Sumatera Selatan", city: "Kabupaten Ogan Komering Ulu Selatan" },
  { province: "Sumatera Selatan", city: "Kabupaten Ogan Ilir" },
  { province: "Sumatera Selatan", city: "Kabupaten Empat Lawang" },
  { province: "Sumatera Selatan", city: "Kabupaten Penukal Abab Lematang Ilir" },
  { province: "Sumatera Selatan", city: "Kabupaten Musi Rawas Utara" },
  { province: "Sumatera Selatan", city: "Kota Palembang" },
  { province: "Sumatera Selatan", city: "Kota Pagar Alam" },
  { province: "Sumatera Selatan", city: "Kota Lubuk Linggau" },
  { province: "Sumatera Selatan", city: "Kota Prabumulih" },
  { province: "Bengkulu", city: "Kabupaten Bengkulu Selatan" },
  { province: "Bengkulu", city: "Kabupaten Rejang Lebong" },
  { province: "Bengkulu", city: "Kabupaten Bengkulu Utara" },
  { province: "Bengkulu", city: "Kabupaten Kaur" },
  { province: "Bengkulu", city: "Kabupaten Seluma" },
  { province: "Bengkulu", city: "Kabupaten Mukomuko" },
  { province: "Bengkulu", city: "Kabupaten Lebong" },
  { province: "Bengkulu", city: "Kabupaten Kepahiang" },
  { province: "Bengkulu", city: "Kabupaten Bengkulu Tengah" },
  { province: "Bengkulu", city: "Kota Bengkulu" },
  { province: "Lampung", city: "Kabupaten Lampung Selatan" },
  { province: "Lampung", city: "Kabupaten Lampung Tengah" },
  { province: "Lampung", city: "Kabupaten Lampung Utara" },
  { province: "Lampung", city: "Kabupaten Lampung Barat" },
  { province: "Lampung", city: "Kabupaten Tulang Bawang" },
  { province: "Lampung", city: "Kabupaten Tanggamus" },
  { province: "Lampung", city: "Kabupaten Lampung Timur" },
  { province: "Lampung", city: "Kabupaten Way Kanan" },
  { province: "Lampung", city: "Kabupaten Pesawaran" },
  { province: "Lampung", city: "Kabupaten Pringsewu" },
  { province: "Lampung", city: "Kabupaten Mesuji" },
  { province: "Lampung", city: "Kabupaten Tulang Bawang Barat" },
  { province: "Lampung", city: "Kabupaten Pesisir Barat" },
  { province: "Lampung", city: "Kota Bandar Lampung" },
  { province: "Lampung", city: "Kota Metro" },
  { province: "Kepulauan Bangka Belitung", city: "Kabupaten Bangka" },
  { province: "Kepulauan Bangka Belitung", city: "Kabupaten Belitung" },
  { province: "Kepulauan Bangka Belitung", city: "Kabupaten Bangka Selatan" },
  { province: "Kepulauan Bangka Belitung", city: "Kabupaten Bangka Tengah" },
  { province: "Kepulauan Bangka Belitung", city: "Kabupaten Bangka Barat" },
  { province: "Kepulauan Bangka Belitung", city: "Kabupaten Belitung Timur" },
  { province: "Kepulauan Bangka Belitung", city: "Kota Pangkal Pinang" },
  { province: "Kepulauan Riau", city: "Kabupaten Bintan" },
  { province: "Kepulauan Riau", city: "Kabupaten Karimun" },
  { province: "Kepulauan Riau", city: "Kabupaten Natuna" },
  { province: "Kepulauan Riau", city: "Kabupaten Lingga" },
  { province: "Kepulauan Riau", city: "Kabupaten Kepulauan Anambas" },
  { province: "Kepulauan Riau", city: "Kota Batam" },
  { province: "Kepulauan Riau", city: "Kota Tanjung Pinang" },
  { province: "DKI Jakarta", city: "Kabupaten Administrasi Kepulauan Seribu" },
  { province: "DKI Jakarta", city: "Kota Administrasi Jakarta Pusat" },
  { province: "DKI Jakarta", city: "Kota Administrasi Jakarta Utara " },
  { province: "DKI Jakarta", city: "Kota Administrasi Jakarta Barat" },
  { province: "DKI Jakarta", city: "Kota Administrasi Jakarta Selatan" },
  { province: "DKI Jakarta", city: "Kota Administrasi Jakarta Timur" },
  { province: "Jawa Barat", city: "Kabupaten Bogor" },
  { province: "Jawa Barat", city: "Kabupaten Sukabumi" },
  { province: "Jawa Barat", city: "Kabupaten Cianjur" },
  { province: "Jawa Barat", city: "Kabupaten Bandung" },
  { province: "Jawa Barat", city: "Kabupaten Garut" },
  { province: "Jawa Barat", city: "Kabupaten Tasikmalaya" },
  { province: "Jawa Barat", city: "Kabupaten Ciamis" },
  { province: "Jawa Barat", city: "Kabupaten Kuningan" },
  { province: "Jawa Barat", city: "Kabupaten Cirebon" },
  { province: "Jawa Barat", city: "Kabupaten Majalengka" },
  { province: "Jawa Barat", city: "Kabupaten Sumedang" },
  { province: "Jawa Barat", city: "Kabupaten Indramayu" },
  { province: "Jawa Barat", city: "Kabupaten Subang" },
  { province: "Jawa Barat", city: "Kabupaten Purwakarta" },
  { province: "Jawa Barat", city: "Kabupaten Karawang" },
  { province: "Jawa Barat", city: "Kabupaten Bekasi" },
  { province: "Jawa Barat", city: "Kabupaten Bandung Barat" },
  { province: "Jawa Barat", city: "Kabupaten Pangandaran" },
  { province: "Jawa Barat", city: "Kota Bogor" },
  { province: "Jawa Barat", city: "Kota Sukabumi" },
  { province: "Jawa Barat", city: "Kota Bandung" },
  { province: "Jawa Barat", city: "Kota Cirebon" },
  { province: "Jawa Barat", city: "Kota Bekasi" },
  { province: "Jawa Barat", city: "Kota Depok" },
  { province: "Jawa Barat", city: "Kota Cimahi" },
  { province: "Jawa Barat", city: "Kota Tasikmalaya" },
  { province: "Jawa Barat", city: "Kota Banjar" },
  { province: "Jawa Tengah", city: "Kabupaten Cilacap" },
  { province: "Jawa Tengah", city: "Kabupaten Banyumas" },
  { province: "Jawa Tengah", city: "Kabupaten Purbalingga" },
  { province: "Jawa Tengah", city: "Kabupaten Banjarnegara" },
  { province: "Jawa Tengah", city: "Kabupaten Kebumen" },
  { province: "Jawa Tengah", city: "Kabupaten Purworejo" },
  { province: "Jawa Tengah", city: "Kabupaten Wonosobo" },
  { province: "Jawa Tengah", city: "Kabupaten Magelang" },
  { province: "Jawa Tengah", city: "Kabupaten Boyolali" },
  { province: "Jawa Tengah", city: "Kabupaten Klaten" },
  { province: "Jawa Tengah", city: "Kabupaten Sukoharjo" },
  { province: "Jawa Tengah", city: "Kabupaten Wonogiri" },
  { province: "Jawa Tengah", city: "Kabupaten Karanganyar" },
  { province: "Jawa Tengah", city: "Kabupaten Sragen" },
  { province: "Jawa Tengah", city: "Kabupaten Grobogan" },
  { province: "Jawa Tengah", city: "Kabupaten Blora" },
  { province: "Jawa Tengah", city: "Kabupaten Rembang" },
  { province: "Jawa Tengah", city: "Kabupaten Pati" },
  { province: "Jawa Tengah", city: "Kabupaten Kudus" },
  { province: "Jawa Tengah", city: "Kabupaten Jepara" },
  { province: "Jawa Tengah", city: "Kabupaten Demak" },
  { province: "Jawa Tengah", city: "Kabupaten Semarang" },
  { province: "Jawa Tengah", city: "Kabupaten Temanggung" },
  { province: "Jawa Tengah", city: "Kabupaten Kendal" },
  { province: "Jawa Tengah", city: "Kabupaten Batang" },
  { province: "Jawa Tengah", city: "Kabupaten Pekalongan" },
  { province: "Jawa Tengah", city: "Kabupaten Pemalang" },
  { province: "Jawa Tengah", city: "Kabupaten Tegal" },
  { province: "Jawa Tengah", city: "Kabupaten Brebes" },
  { province: "Jawa Tengah", city: "Kota Magelang" },
  { province: "Jawa Tengah", city: "Kota Surakarta" },
  { province: "Jawa Tengah", city: "Kota Salatiga" },
  { province: "Jawa Tengah", city: "Kota Semarang" },
  { province: "Jawa Tengah", city: "Kota Pekalongan" },
  { province: "Jawa Tengah", city: "Kota Tegal" },
  { province: "Daerah Istimewa Yogyakarta", city: "Kabupaten Kulon Progo" },
  { province: "Daerah Istimewa Yogyakarta", city: "Kabupaten Bantul" },
  { province: "Daerah Istimewa Yogyakarta", city: "Kabupaten Gunungkidul" },
  { province: "Daerah Istimewa Yogyakarta", city: "Kabupaten Sleman" },
  { province: "Daerah Istimewa Yogyakarta", city: "Kota Yogyakarta" },
  { province: "Jawa Timur", city: "Kabupaten Pacitan" },
  { province: "Jawa Timur", city: "Kabupaten Ponorogo" },
  { province: "Jawa Timur", city: "Kabupaten Trenggalek" },
  { province: "Jawa Timur", city: "Kabupaten Tulungagung" },
  { province: "Jawa Timur", city: "Kabupaten Blitar" },
  { province: "Jawa Timur", city: "Kabupaten Kediri" },
  { province: "Jawa Timur", city: "Kabupaten Malang" },
  { province: "Jawa Timur", city: "Kabupaten Lumajang" },
  { province: "Jawa Timur", city: "Kabupaten Jember" },
  { province: "Jawa Timur", city: "Kabupaten Banyuwangi" },
  { province: "Jawa Timur", city: "Kabupaten Bondowoso" },
  { province: "Jawa Timur", city: "Kabupaten Situbondo" },
  { province: "Jawa Timur", city: "Kabupaten Probolinggo" },
  { province: "Jawa Timur", city: "Kabupaten Pasuruan" },
  { province: "Jawa Timur", city: "Kabupaten Sidoarjo" },
  { province: "Jawa Timur", city: "Kabupaten Mojokerto" },
  { province: "Jawa Timur", city: "Kabupaten Jombang" },
  { province: "Jawa Timur", city: "Kabupaten Nganjuk" },
  { province: "Jawa Timur", city: "Kabupaten Madiun" },
  { province: "Jawa Timur", city: "Kabupaten Magetan" },
  { province: "Jawa Timur", city: "Kabupaten Ngawi" },
  { province: "Jawa Timur", city: "Kabupaten Bojonegoro" },
  { province: "Jawa Timur", city: "Kabupaten Tuban" },
  { province: "Jawa Timur", city: "Kabupaten Lamongan" },
  { province: "Jawa Timur", city: "Kabupaten Gresik" },
  { province: "Jawa Timur", city: "Kabupaten Bangkalan" },
  { province: "Jawa Timur", city: "Kabupaten Sampang" },
  { province: "Jawa Timur", city: "Kabupaten Pamekasan" },
  { province: "Jawa Timur", city: "Kabupaten Sumenep" },
  { province: "Jawa Timur", city: "Kota Kediri" },
  { province: "Jawa Timur", city: "Kota Blitar" },
  { province: "Jawa Timur", city: "Kota Malang" },
  { province: "Jawa Timur", city: "Kota Probolinggo" },
  { province: "Jawa Timur", city: "Kota Pasuruan" },
  { province: "Jawa Timur", city: "Kota Mojokerto" },
  { province: "Jawa Timur", city: "Kota Madiun" },
  { province: "Jawa Timur", city: "Kota Surabaya" },
  { province: "Jawa Timur", city: "Kota Batu" },
  { province: "Banten", city: "Kabupaten Pandeglang" },
  { province: "Banten", city: "Kabupaten Lebak" },
  { province: "Banten", city: "Kabupaten Tangerang" },
  { province: "Banten", city: "Kabupaten Serang" },
  { province: "Banten", city: "Kota Tangerang" },
  { province: "Banten", city: "Kota Cilegon" },
  { province: "Banten", city: "Kota Serang" },
  { province: "Banten", city: "Kota Tangerang Selatan" },
  { province: "Bali", city: "Kabupaten Jembrana" },
  { province: "Bali", city: "Kabupaten Tabanan" },
  { province: "Bali", city: "Kabupaten Badung" },
  { province: "Bali", city: "Kabupaten Gianyar" },
  { province: "Bali", city: "Kabupaten Klungkung" },
  { province: "Bali", city: "Kabupaten Bangli" },
  { province: "Bali", city: "Kabupaten Karangasem" },
  { province: "Bali", city: "Kabupaten Buleleng" },
  { province: "Bali", city: "Kota Denpasar" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Lombok Barat" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Lombok Tengah" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Lombok Timur" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Sumbawa" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Dompu" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Bima" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Sumbawa Barat" },
  { province: "Nusa Tenggara Barat", city: "Kabupaten Lombok Utara" },
  { province: "Nusa Tenggara Barat", city: "Kota Mataram" },
  { province: "Nusa Tenggara Barat", city: "Kota Bima" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Kupang" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Timor Tengah Selatan" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Timor Tengah Utara" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Belu" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Alor" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Flores Timur" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Sikka" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Ende" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Ngada" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Manggarai" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Sumba Timur" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Sumba Barat" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Lembata" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Rote Ndao" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Manggarai Barat" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Nagekeo" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Sumba Tengah" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Sumba Barat Daya" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Manggarai Timur" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Sabu Raijua" },
  { province: "Nusa Tenggara Timur", city: "Kabupaten Malaka" },
  { province: "Nusa Tenggara Timur", city: "Kota Kupang" },
  { province: "Kalimantan Barat", city: "Kabupaten Sambas" },
  { province: "Kalimantan Barat", city: "Kabupaten Mempawah" },
  { province: "Kalimantan Barat", city: "Kabupaten Sanggau" },
  { province: "Kalimantan Barat", city: "Kabupaten Ketapang" },
  { province: "Kalimantan Barat", city: "Kabupaten Sintang" },
  { province: "Kalimantan Barat", city: "Kabupaten Kapuas Hulu" },
  { province: "Kalimantan Barat", city: "Kabupaten Bengkayang" },
  { province: "Kalimantan Barat", city: "Kabupaten Landak" },
  { province: "Kalimantan Barat", city: "Kabupaten Sekadau" },
  { province: "Kalimantan Barat", city: "Kabupaten Melawi" },
  { province: "Kalimantan Barat", city: "Kabupaten Kayong Utara" },
  { province: "Kalimantan Barat", city: "Kabupaten Kubu Raya" },
  { province: "Kalimantan Barat", city: "Kota Pontianak" },
  { province: "Kalimantan Barat", city: "Kota Singkawang" },
  { province: "Kalimantan Tengah", city: "Kabupaten Kotawaringin Barat" },
  { province: "Kalimantan Tengah", city: "Kabupaten Kotawaringin Timur" },
  { province: "Kalimantan Tengah", city: "Kabupaten Kapuas" },
  { province: "Kalimantan Tengah", city: "Kabupaten Barito Selatan" },
  { province: "Kalimantan Tengah", city: "Kabupaten Barito Utara" },
  { province: "Kalimantan Tengah", city: "Kabupaten Katingan" },
  { province: "Kalimantan Tengah", city: "Kabupaten Seruyan" },
  { province: "Kalimantan Tengah", city: "Kabupaten Sukamara" },
  { province: "Kalimantan Tengah", city: "Kabupaten Lamandau" },
  { province: "Kalimantan Tengah", city: "Kabupaten Gunung Mas" },
  { province: "Kalimantan Tengah", city: "Kabupaten Pulang Pisau" },
  { province: "Kalimantan Tengah", city: "Kabupaten Murung Raya" },
  { province: "Kalimantan Tengah", city: "Kabupaten Barito Timur" },
  { province: "Kalimantan Tengah", city: "Kota Palangkaraya" },
  { province: "Kalimantan Selatan", city: "Kabupaten Tanah Laut" },
  { province: "Kalimantan Selatan", city: "Kabupaten Kotabaru" },
  { province: "Kalimantan Selatan", city: "Kabupaten Banjar" },
  { province: "Kalimantan Selatan", city: "Kabupaten Barito Kuala" },
  { province: "Kalimantan Selatan", city: "Kabupaten Tapin" },
  { province: "Kalimantan Selatan", city: "Kabupaten Hulu Sungai Selatan" },
  { province: "Kalimantan Selatan", city: "Kabupaten Hulu Sungai Tengah" },
  { province: "Kalimantan Selatan", city: "Kabupaten Hulu Sungai Utara" },
  { province: "Kalimantan Selatan", city: "Kabupaten Tabalong" },
  { province: "Kalimantan Selatan", city: "Kabupaten Tanah Bumbu" },
  { province: "Kalimantan Selatan", city: "Kabupaten Balangan" },
  { province: "Kalimantan Selatan", city: "Kota Banjarmasin" },
  { province: "Kalimantan Selatan", city: "Kota Banjarbaru" },
  { province: "Kalimantan Timur", city: "Kabupaten Paser" },
  { province: "Kalimantan Timur", city: "Kabupaten Kutai Kartanegara" },
  { province: "Kalimantan Timur", city: "Kabupaten Berau" },
  { province: "Kalimantan Timur", city: "Kabupaten Kutai Barat" },
  { province: "Kalimantan Timur", city: "Kabupaten Kutai Timur" },
  { province: "Kalimantan Timur", city: "Kabupaten Penajam Paser Utara" },
  { province: "Kalimantan Timur", city: "Kabupaten Mahakam Ulu" },
  { province: "Kalimantan Timur", city: "Kota Balikpapan" },
  { province: "Kalimantan Timur", city: "Kota Samarinda" },
  { province: "Kalimantan Timur", city: "Kota Bontang" },
  { province: "Kalimantan Utara", city: "Kabupaten Bulungan" },
  { province: "Kalimantan Utara", city: "Kabupaten Malinau" },
  { province: "Kalimantan Utara", city: "Kabupaten Nunukan" },
  { province: "Kalimantan Utara", city: "Kabupaten Tana Tidung" },
  { province: "Kalimantan Utara", city: "Kota Tarakan" },
  { province: "Sulawesi Utara", city: "Kabupaten Bolaang Mongondow" },
  { province: "Sulawesi Utara", city: "Kabupaten Minahasa" },
  { province: "Sulawesi Utara", city: "Kabupaten Kepulauan Sangihe" },
  { province: "Sulawesi Utara", city: "Kabupaten Kepulauan Talaud" },
  { province: "Sulawesi Utara", city: "Kabupaten Minahasa Selatan" },
  { province: "Sulawesi Utara", city: "Kabupaten Minahasa Utara" },
  { province: "Sulawesi Utara", city: "Kabupaten Minahasa Tenggara" },
  { province: "Sulawesi Utara", city: "Kabupaten Bolaang Mongondow Utara" },
  { province: "Sulawesi Utara", city: "Kabupaten Kep. Siau Tagulandang Biaro" },
  { province: "Sulawesi Utara", city: "Kabupaten Bolaang Mongondow Timur" },
  { province: "Sulawesi Utara", city: "Kabupaten Bolaang Mongondow Selatan" },
  { province: "Sulawesi Utara", city: "Kota Manado" },
  { province: "Sulawesi Utara", city: "Kota Bitung" },
  { province: "Sulawesi Utara", city: "Kota Tomohon" },
  { province: "Sulawesi Utara", city: "Kota Kotamobagu" },
  { province: "Sulawesi Tengah", city: "Kabupaten Banggai" },
  { province: "Sulawesi Tengah", city: "Kabupaten Poso" },
  { province: "Sulawesi Tengah", city: "Kabupaten Donggala" },
  { province: "Sulawesi Tengah", city: "Kabupaten Toli-Toli" },
  { province: "Sulawesi Tengah", city: "Kabupaten Buol" },
  { province: "Sulawesi Tengah", city: "Kabupaten Morowali" },
  { province: "Sulawesi Tengah", city: "Kabupaten Banggai Kepulauan" },
  { province: "Sulawesi Tengah", city: "Kabupaten Parigi Moutong" },
  { province: "Sulawesi Tengah", city: "Kabupaten Tojo Una Una" },
  { province: "Sulawesi Tengah", city: "Kabupaten Sigi" },
  { province: "Sulawesi Tengah", city: "Kabupaten Banggai Laut" },
  { province: "Sulawesi Tengah", city: "Kabupaten Morowali Utara" },
  { province: "Sulawesi Tengah", city: "Kota Palu" },
  { province: "Sulawesi Selatan", city: "Kabupaten Kepulauan Selayar" },
  { province: "Sulawesi Selatan", city: "Kabupaten Bulukumba" },
  { province: "Sulawesi Selatan", city: "Kabupaten Bantaeng" },
  { province: "Sulawesi Selatan", city: "Kabupaten Jeneponto" },
  { province: "Sulawesi Selatan", city: "Kabupaten Takalar" },
  { province: "Sulawesi Selatan", city: "Kabupaten Gowa" },
  { province: "Sulawesi Selatan", city: "Kabupaten Sinjai" },
  { province: "Sulawesi Selatan", city: "Kabupaten Bone" },
  { province: "Sulawesi Selatan", city: "Kabupaten Maros" },
  { province: "Sulawesi Selatan", city: "Kabupaten Pangkajene dan Kepulauan" },
  { province: "Sulawesi Selatan", city: "Kabupaten Barru" },
  { province: "Sulawesi Selatan", city: "Kabupaten Soppeng" },
  { province: "Sulawesi Selatan", city: "Kabupaten Wajo" },
  { province: "Sulawesi Selatan", city: "Kabupaten Sidenreng Rappang" },
  { province: "Sulawesi Selatan", city: "Kabupaten Pinrang" },
  { province: "Sulawesi Selatan", city: "Kabupaten Enrekang" },
  { province: "Sulawesi Selatan", city: "Kabupaten Luwu" },
  { province: "Sulawesi Selatan", city: "Kabupaten Tana Toraja" },
  { province: "Sulawesi Selatan", city: "Kabupaten Luwu Utara" },
  { province: "Sulawesi Selatan", city: "Kabupaten Luwu Timur" },
  { province: "Sulawesi Selatan", city: "Kabupaten Toraja Utara" },
  { province: "Sulawesi Selatan", city: "Kota Makassar" },
  { province: "Sulawesi Selatan", city: "Kota Parepare" },
  { province: "Sulawesi Selatan", city: "Kota Palopo" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Kolaka" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Konawe" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Muna" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Buton" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Konawe Selatan" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Bombana" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Wakatobi" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Kolaka Utara" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Konawe Utara" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Buton Utara" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Kolaka Timur" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Konawe Kepulauan" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Muna Barat" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Buton Tengah" },
  { province: "Sulawesi Tenggara", city: "Kabupaten Buton Selatan" },
  { province: "Sulawesi Tenggara", city: "Kota Kendari" },
  { province: "Sulawesi Tenggara", city: "Kota Bau Bau" },
  { province: "Gorontalo", city: "Kabupaten Gorontalo" },
  { province: "Gorontalo", city: "Kabupaten Boalemo" },
  { province: "Gorontalo", city: "Kabupaten Bone Bolango" },
  { province: "Gorontalo", city: "Kabupaten Pohuwato" },
  { province: "Gorontalo", city: "Kabupaten Gorontalo Utara" },
  { province: "Gorontalo", city: "Kota Gorontalo" },
  { province: "Sulawesi Barat", city: "Kabupaten Pasangkayu" },
  { province: "Sulawesi Barat", city: "Kabupaten Mamuju" },
  { province: "Sulawesi Barat", city: "Kabupaten Mamasa" },
  { province: "Sulawesi Barat", city: "Kabupaten Polewali Mandar" },
  { province: "Sulawesi Barat", city: "Kabupaten Majene" },
  { province: "Sulawesi Barat", city: "Kabupaten Mamuju Tengah" },
  { province: "Maluku", city: "Kabupaten Maluku Tengah" },
  { province: "Maluku", city: "Kabupaten Maluku Tenggara" },
  { province: "Maluku", city: "Kabupaten Kepulauan Tanimbar" },
  { province: "Maluku", city: "Kabupaten Buru" },
  { province: "Maluku", city: "Kabupaten Seram Bagian Timur" },
  { province: "Maluku", city: "Kabupaten Seram Bagian Barat" },
  { province: "Maluku", city: "Kabupaten Kepulauan Aru" },
  { province: "Maluku", city: "Kabupaten Maluku Barat Daya" },
  { province: "Maluku", city: "Kabupaten Buru Selatan" },
  { province: "Maluku", city: "Kota Ambon" },
  { province: "Maluku", city: "Kota Tual" },
  { province: "Maluku Utara", city: "Kabupaten Halmahera Barat" },
  { province: "Maluku Utara", city: "Kabupaten Halmahera Tengah" },
  { province: "Maluku Utara", city: "Kabupaten Halmahera Utara" },
  { province: "Maluku Utara", city: "Kabupaten Halmahera Selatan" },
  { province: "Maluku Utara", city: "Kabupaten Kepulauan Sula" },
  { province: "Maluku Utara", city: "Kabupaten Halmahera Timur" },
  { province: "Maluku Utara", city: "Kabupaten Pulau Morotai" },
  { province: "Maluku Utara", city: "Kabupaten Pulau Taliabu" },
  { province: "Maluku Utara", city: "Kota Ternate" },
  { province: "Maluku Utara", city: "Kota Tidore Kepulauan" },
  { province: "Papua", city: "Kabupaten Jayapura" },
  { province: "Papua", city: "Kabupaten Kepulauan Yapen" },
  { province: "Papua", city: "Kabupaten Biak Numfor" },
  { province: "Papua", city: "Kabupaten Sarmi" },
  { province: "Papua", city: "Kabupaten Keerom" },
  { province: "Papua", city: "Kabupaten Waropen" },
  { province: "Papua", city: "Kabupaten Supiori" },
  { province: "Papua", city: "Kabupaten Mamberamo Raya" },
  { province: "Papua", city: "Kota Jayapura" },
  { province: "Papua Barat", city: "Kabupaten Manokwari" },
  { province: "Papua Barat", city: "Kabupaten Fak Fak" },
  { province: "Papua Barat", city: "Kabupaten Teluk Bintuni" },
  { province: "Papua Barat", city: "Kabupaten Teluk Wondama" },
  { province: "Papua Barat", city: "Kabupaten Kaimana" },
  { province: "Papua Barat", city: "Kabupaten Manokwari Selatan" },
  { province: "Papua Barat", city: "Kabupaten Pegunungan Arfak" },
  { province: "Papua Selatan", city: "Kabupaten Merauke" },
  { province: "Papua Selatan", city: "Kabupaten Boven Digoel" },
  { province: "Papua Selatan", city: "Kabupaten Mappi" },
  { province: "Papua Selatan", city: "Kabupaten Asmat" },
  { province: "Papua Tengah", city: "Kabupaten Nabire" },
  { province: "Papua Tengah", city: "Kabupaten Puncak Jaya" },
  { province: "Papua Tengah", city: "Kabupaten Paniai" },
  { province: "Papua Tengah", city: "Kabupaten Mimika" },
  { province: "Papua Tengah", city: "Kabupaten Puncak" },
  { province: "Papua Tengah", city: "Kabupaten Dogiyai" },
  { province: "Papua Tengah", city: "Kabupaten Intan Jaya" },
  { province: "Papua Tengah", city: "Kabupaten Deiyai" },
  { province: "Papua Pegunungan", city: "Kabupaten Jayawijaya" },
  { province: "Papua Pegunungan", city: "Kabupaten Pegunungan Bintang" },
  { province: "Papua Pegunungan", city: "Kabupaten Yahukimo" },
  { province: "Papua Pegunungan", city: "Kabupaten Tolikara" },
  { province: "Papua Pegunungan", city: "Kabupaten Mamberamo Tengah" },
  { province: "Papua Pegunungan", city: "Kabupaten Yalimo" },
  { province: "Papua Pegunungan", city: "Kabupaten Lanny Jaya" },
  { province: "Papua Pegunungan", city: "Kabupaten Nduga" },
  { province: "Papua Barat Daya", city: "Kabupaten Sorong" },
  { province: "Papua Barat Daya", city: "Kabupaten Sorong Selatan" },
  { province: "Papua Barat Daya", city: "Kabupaten Raja Ampat" },
  { province: "Papua Barat Daya", city: "Kabupaten Tambrauw" },
  { province: "Papua Barat Daya", city: "Kabupaten Maybrat" },
  { province: "Papua Barat Daya", city: "Kota Sorong" },
]
